[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/"
]

# Solidity version
solc_version = "0.8.25"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Testing settings
verbosity = 2
gas_reports = ["*"]

# Fuzz testing
fuzz = { runs = 256 }

# File permissions for scripts
fs_permissions = [{ access = "read-write", path = "./" }]

# Network configurations
[rpc_endpoints]
lisk-sepolia = "https://rpc.sepolia.lisk.com"
local = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

[etherscan]
lisk-sepolia = { key = "${LISK_ETHERSCAN_API_KEY}", url = "https://sepolia-blockscout.lisk.com/api" }